### ISSUE TITLE
Evaluation result

### ISSUE THREAD

**Issue by wenyiwangbst** [TuSimple/SimpleTrack#10]
Hi, thank you for sharing your code. I have test run the code on the full waymo validation dataset and using the detection you send to me(thanks for doing that) and use waymo evaluation metrics to do the evaluation. The result I got shows as following:
![2022-03-03 09-54-17 的屏幕截图](https://user-images.githubusercontent.com/98773595/156623180-4ae8ac1b-603b-43ce-91ab-d0fa1f7e2235.png)
But in the paper the L2 Vehicle could achieve around 0.56 in MOTA which is about 3.5% higher than my implement. 
![2022-03-03 09-59-18 的屏幕截图](https://user-images.githubusercontent.com/98773595/156624224-6af8a3f2-e073-4c63-9915-ef1c103aee23.png)
Can I ask if the released code is of the same setting in parameter as the one in the paper and what evaluation method are you guys using.
Thanks again for all your work and help.

**Comment by ziqipang** [comment]
@wenyiwangbst Which config file did you use?

**Comment by wenyiwangbst** [comment]
![2022-03-07 09-41-03 的屏幕截图](https://user-images.githubusercontent.com/98773595/157088272-015f9702-fa55-4c36-b52a-a0db63e076b2.png)

**Comment by ziqipang** [comment]
@wenyiwangbst  Please use `vc_kf_giou` for vehicles/cyclists and `pd_kf_giou` for pedestrians. I tested this repo on my side before open sourcing. If you still cannot re-produce, I will get back after eccv deadline.

**Comment by BaiLiping** [comment]
> Hi, thank you for sharing your code. I have test run the code on the full waymo validation dataset and using the detection you send to me(thanks for doing that) and use waymo evaluation metrics to do the evaluation. The result I got shows as following: ![2022-03-03 09-54-17 的屏幕截图](https://user-images.githubusercontent.com/98773595/156623180-4ae8ac1b-603b-43ce-91ab-d0fa1f7e2235.png) But in the paper the L2 Vehicle could achieve around 0.56 in MOTA which is about 3.5% higher than my implement. ![2022-03-03 09-59-18 的屏幕截图](https://user-images.githubusercontent.com/98773595/156624224-6af8a3f2-e073-4c63-9915-ef1c103aee23.png) Can I ask if the released code is of the same setting in parameter as the one in the paper and what evaluation method are you guys using. Thanks again for all your work and help.

hi wenyi, any chance you can pass along that waymo inference file to me? my email is blp_engineer@outlook.com Thanks.

**Comment by ziqipang** [comment]
@BaiLiping @wenyiwangbst I just added the generated results at [README](https://github.com/TuSimple/SimpleTrack#inference-on-waymo-open-dataset-and-nuscenes). Please check out the dropbox links and see if they are helpful.

**Comment by BaiLiping** [comment]
Thanks a lot.
