### ISSUE TITLE
Ground Truth Information

### ISSUE THREAD

**Issue by BrunoComCue** [TuSimple/SimpleTrack#11]
Hi,
First of all, thank you for sharing your code.

I have been trying to preprocess the WOD data but I am stuck on the second step (decode the ground truth), where I am getting the following error: 
`Traceback (most recent call last):`
 ` File "gt_bin_decode.py", line 129, in <module>`
`      main(args.file_path, out_folder, args.data_folder)`
  `File "gt_bin_decode.py", line 81, in main`
`    segment_name = segment_name_list[val_index]`
`TypeError: list indices must be integers or slices, not NoneType`

Any idea what could I be? 
I tried to track the error and I think it could have to do with the .json files, somehow.

**Comment by ziqipang** [comment]
I will get back to this after eccv deadline.

**Comment by BrunoComCue** [comment]
I found my mistake. I was just preprocessing part of the validation data, not the whole 202 files. For the first preprocessing step is fine but when decoding the GT information, it was looking for segments that weren't there. Now it is working.
