### ISSUE TITLE
threshold_high is never used in NMS?

### ISSUE THREAD

**Issue by xinshuoweng** [TuSimple/SimpleTrack#12]
Hi Ziqi, 

I have one simple question regarding the NMS. Because the threshold_high is set to 1.0, it seems that the block of code below is never used in NMS:
https://github.com/TuSimple/SimpleTrack/blob/3b44d6d197b06501f01b939e2f1da764e44ac5dd/mot_3d/preprocessing/nms.py#L47-L71
Could you please illustrate a bit more how and where the above code is useful?

Thanks!

**Comment by Lzc6996** [comment]
@xinshuoweng 
About the weighted-NMS, you can refer the **Bounding box voting** in [Object detection via a multi-region & semantic segmentation-aware CNN model](https://arxiv.org/pdf/1505.01749.pdf)

**Comment by ziqipang** [comment]
Close due to no action.
