### ISSUE TITLE
file_path文件

### ISSUE THREAD

**Issue by TerryYiDa** [TuSimple/SimpleTrack#20]
你好，如果我在v1.0-mini中测试，请问在Data Processing中nuscene的file_path文件怎么获取？

**Comment by ziqipang** [comment]
我们没有v1.0-mini的detection文件，在[README](https://github.com/TuSimple/SimpleTrack#inference-on-waymo-open-dataset-and-nuscenes)的nuScenes Dropbox Link里面我们提供了validation set的detection file.
