### ISSUE TITLE
I din't find the two-stage association part in the dev-branch's code, is this part not pushed yet ?

### ISSUE THREAD

**Issue by a954217436** [TuSimple/SimpleTrack#3]
Thanks for replying

**Comment by ziqipang** [comment]
Thank you for your interest! Sorry for not being able to provide a detailed explanation, as I am still cleaning the code and writing documentation (should be finished in January).

The part you are looking for should be in `mot_3d/redundancy/redundancy.py`, the function `motion_model_redundancy`. Please let me know if you have further questions.

**Comment by ziqipang** [comment]
@a954217436 Sorry for not @ your before, could you check if this is helpful for you?

**Comment by a954217436** [comment]
Thanks for replying. I'll study the code and then reply you~
And I'm looking forward to your cleaning code.

**Comment by a954217436** [comment]
OK, I understand the RedundancyModule's function now. This is what I'm looking for, thanks a lot!

**Comment by ziqipang** [comment]
@a954217436 Thanks! By the way, I have updated a version of clean code to the main branch. Feel free to check it out!
