### ISSUE TITLE
fail to download data from Dropbox link

### ISSUE THREAD

**Issue by sunyafeihit** [TuSimple/SimpleTrack#41]
Dropbox link 的数据无法下载，哪位大神可以提供一下详细下载步骤，感谢

**Comment by ziqipang** [comment]
@sunyafeihit If you are in mainland China, a VPN might be required. Could you use a VPN and double-check this?

**Comment by sunyafeihit** [comment]
> @sunyafeihit If you are in mainland China, a VPN might be required. Could you use a VPN and double-check this?

I have tried and it works. Thank you very much!
