### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (40,) + inhomogeneous part.

### ISSUE THREAD

**Issue by jesanli** [TuSimple/SimpleTrack#44]
![图片](https://github.com/tusen-ai/SimpleTrack/assets/114420367/8840eeb2-165e-475f-a7a7-1d7c41a08af5)
when I use "bash nuscenes_preprocess.sh ${raw_data_dir} ${data_dir_2hz} ${data_dir_20hz}" occur this problem
my numpy version==1.19.5
![图片](https://github.com/tusen-ai/SimpleTrack/assets/114420367/c94b8fae-0e22-4f0e-85a3-fd8fd204949b)

**Comment by jesanli** [comment]
my command is "bash nuscenes_preprocess.sh /home/jesanli/SimpleTrack/SimpleTrack-main/data/nuscenes/ data_nus_2hz data_nus_20hz" as the results,the 2hz as same as 20hz,there are all 150 files ,Could you tell me what's the different? Thanks

**Comment by jesanli** [comment]
yeah i have solved it by turning the version of numpy!

**Comment by ziqipang** [comment]
@jesanli Glad to know that you have addressed this!

**Comment by mx2013713828** [comment]
> yeah i have solved it by turning the version of numpy!

Hi,what is your numpy version? I got same problem.
Thanks for your reply~!

**Comment by jesanli** [comment]
> > yeah i have solved it by turning the version of numpy!
> 
> Hi,what is your numpy version? I got same problem. Thanks for your reply~!

you can use numpy==1.19.5 when demo.py ,others you can use numpy==1.24.4

**Comment by mx2013713828** [comment]
> > > yeah i have solved it by turning the version of numpy!
> > 
> > 
> > Hi,what is your numpy version? I got same problem. Thanks for your reply~!
> 
> you can use numpy==1.19.5 when demo.py ,others you can use numpy==1.24.4

Thanks a lot ,I will try!
