### ISSUE TITLE
Can I apply SimplyTrack with pointpillar detector result ?

### ISSUE THREAD

**Issue by mx2013713828** [TuSimple/SimpleTrack#46]
Greak work! 
I already have pointpillar detector trained in our own dataset, and I want using your SimpleTrack, what should I prepare?
By the way, our detection result format is 'x,y,z,w,l,h,roll,pitch,yaw,score'.
Waiting for your reply!~

**Comment by ziqipang** [comment]
@mx2013713828 Thanks! Please convert the detection results into the box format then you are good to go. https://github.com/tusen-ai/SimpleTrack/blob/main/mot_3d/data_protos/bbox.py

**Comment by mx2013713828** [comment]
> @mx2013713828 Thanks! Please convert the detection results into the box format then you are good to go. https://github.com/tusen-ai/SimpleTrack/blob/main/mot_3d/data_protos/bbox.py

Thank you for your reply. During this period, I have understood your code and applied it to my detection results. 
Anyway, thank you!
