### ISSUE TITLE
关于iou3d函数的一行代码

### ISSUE THREAD

**Issue by OriginSound** [TuSimple/SimpleTrack#5]
您好，我想请问一下 mot_3d/utils/geometry.py文件的 iou3d函数，前两行代码如下
boxa_corners = np.array(BBox.box2corners2d(box_a))
boxb_corners = np.array(BBox.box2corners2d(box_b))[:, :2]
第一行不需要进行一个切片操作吗？

**Comment by ziqipang** [comment]
@OriginSound 请问切片操作是什么意思？

**Comment by ziqipang** [comment]
@OriginSound 确实切片会更严谨，但是我测试了一下，这样应该不会报错/对结果也没有影响，可以放心使用。多谢找出来，下一个版本会把这个修一下。

**Comment by OriginSound** [comment]
我还想问一下iou3d函数的这一行代码：
overlap_height = max(0, min((za + ha / 2) - (zb - hb / 2), (zb + hb / 2) - (za - ha / 2)))
算重叠的高度的话，用下面的写法会不会更好一点
overlap_height = max(0, min(za + ha / 2, zb + hb / 2) - max(za - ha / 2, zb - hb / 2) )
