### ISSUE TITLE
Error during exporting detection

### ISSUE THREAD

**Issue by wenyiwangbst** [TuSimple/SimpleTrack#8]
Hi, I use center point to generate output a bin output as well. I try to use the detection.py to export the detection information but return error during saving. I look at the code and seems the frame_number is always None. So ts_info[segment_name][_j]  is never equal to current object's time_stamp. Can I ask how to solve this problem? 
Thank you so much for make the code public and for helping
![2022-02-18 17-43-29 的屏幕截图](https://user-images.githubusercontent.com/98773595/154781187-fe4cc378-ac49-4fb6-acde-ca734b0416b2.png)

**Comment by ziqipang** [comment]
@wenyiwangbst From what you have described, you may have to run [timestamp preprocessing](https://github.com/TuSimple/SimpleTrack/blob/e0ecd96d78eb6ad16303d930e8423376eba21e66/preprocessing/waymo_data/waymo_preprocess.sh#L9) before exporting the detection. A short explanation is: the code for exporting detection relies on the preprocessed timestamps.

**Comment by wenyiwangbst** [comment]
Hi, Thanks for replying. Before exporting the detection, I already run the waymo_preprocess.sh file and generate three folder ego_info, pc and ts_info folder. Is it possible to send me the detection.bin file you use to let me check if it's the problem of the way I generate detection file using centerpoint? My Email is wenyi.wang1998@outlook.com. Thank you again for your helping.

**Comment by ziqipang** [comment]
@wenyiwangbst I just sent you the file via email.
