### ISSUE TITLE
How to get the json format detection files of NuScenes

### ISSUE THREAD

**Issue by liangchunlan** [TuSimple/SimpleTrack#9]
[](https://github.com/TuSimple/SimpleTrack/blob/main/docs/data_preprocess.md#1-preprocessing)nuScenes
1. Preprocessing
![image](https://user-images.githubusercontent.com/73703290/154908176-bf9717b9-d2eb-4d6e-9996-498145cbf169.png)

2. Detection
python detection.py --raw_data_folder ${raw_data_dir} --data_folder ${data_dir_2hz} --det_name ${name} --file_path ${file_path} --mode 2hz --velo
**How can i get the detection file(in code, this default is val.json)**
3. [SimpleTrack](https://github.com/TuSimple/SimpleTrack)/[docs](https://github.com/TuSimple/SimpleTrack/tree/main/docs)/nuScenes.md
```python
python tools/nuscenes_result_creation.py \
    --name SimpleTrack2Hz \
    --name result_folder ${nuscenes_result_dir} \
    --data_folder ${nuscenes2hz_data_dir}
```
=================>>>>>>(i think)
```python
python tools/nuscenes_result_creation.py \
    --name SimpleTrack2Hz \
    --result_folder ${nuscenes_result_dir} \
    --data_folder ${nuscenes2hz_data_dir}
```
4. How do I evaluate NuScenes
5. Look forward to your help

**Comment by ziqipang** [comment]
1. Where to get the detection file? The detection files are generated by your own detector following the nuScenes format. Some public released detectors also release their files, such as [CenterPoint](https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/README.md).
2. How to evaluate nuScenes? After [converting the tracking result to nuScenes format](https://github.com/TuSimple/SimpleTrack/blob/main/docs/nuScenes.md), you will get a .json file following the nuScenes tracking specifications. Then you may need to refer to the nuScenes official repo [nuscenes-devkit](https://github.com/nutonomy/nuscenes-devkit) for evaluating the tracking results with the .json you just produced.

@liangchunlan Hope the above information is helpful.

**Comment by ziqipang** [comment]
Close due to inactivity.
